server:
  port: 8080
  servlet:
    context-path: /testproject
    
spring:
  application:
    name: springboot-demo 

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.22:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: hikariDataSource
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: 192.168.56.22
    port: 6379
    password: 123456
    timeout: 6000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
        
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.model
  
logging:
  level:
    com:
      example:
        mapper: debug
        