/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.sub.project;

import org.junit.Test;

import com.example.DemoLibrary;

import static org.junit.Assert.*;

/**
 * @Description: TODO(这里用一句话描述这个类的作用)
 * @author ThinkPad
 * Date:2020年2月1日 下午4:26:31
 */

public class DemoLibraryTest {
    @Test public void testSomeLibraryMethod() {
        DemoLibrary classUnderTest = new DemoLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
