server:
  port: 9100

spring:
  application:
    name: mybatis-plus

  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          #driver-class-name: org.h2.Driver
          #url: jdbc:h2:mem:test
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:h2:mem:test
          schema: classpath:db/schema-h2.sql
          data: classpath:db/data-h2.sql
          username: root
          password: test
          hikari:
            maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
            idle-timeout: 30000
            pool-name: hikariDataSource
            connection-timeout: 30000
            connection-test-query: SELECT 1
          type: com.zaxxer.hikari.HikariDataSource
        slave:
          #driver-class-name: com.mysql.cj.jdbc.Driver
          #url: jdbc:mysql://192.168.56.22:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://192.168.56.22:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: 123456
          hikari:
            maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
            idle-timeout: 30000
            pool-name: hikariDataSource
            connection-timeout: 30000
            connection-test-query: SELECT 1
          type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      # 主键策略
      id-type: none
      # 表名前缀
      table-prefix: t_
      # 表名是否使用下划线间隔，默认：是
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1

logging:
  file: logs/sys.log
  level:
    com:
      example:
        demo:
          mybatisplus:
            dao: debug
