spring:
  cloud:
    stream:
      bindings:
        myInput:
          destination: minestream
        myOutput:
          destination: minestream

    bus:
      enabled: true
      trace: 
        enabled: true

  redis:
    host: 192.168.56.22
    port: 6379
    password: 123456

  rabbitmq:
    host: 192.168.56.26
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: /

  sleuth:
    sampler:
      probability: 1  #采样频率
    web:
      enabled: true

#  zipkin:
#    base-url: http://localhost:9411/

  zipkin:
    sender:
      type: rabbit

