/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

/**
 * @Description: TODO(这里用一句话描述这个类的作用)
 * @author ThinkPad
 * Date:2020年2月1日 下午4:26:31
 */

public class DemoLibrary {
    public boolean someLibraryMethod() {
        return true;
    }
}
