server:
  port: 8045

spring:
  application:
    name: demo-gateway

  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8769

  cloud:
    consul: 
      host: 192.168.56.28
      port: 8500
      discovery:
        acl-token: 47eca91b-a5e7-e82d-6424-dba7637e0737
        register: true
        hostname: 192.168.56.1
        serviceName: ${spring.application.name}
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.consul.discovery.hostname}
        healthCheckInterval: 15s

    gateway:
#        discovery:
#          locator:
#            enabled: true # 开启通过服务中心的自动根据 serviceId 创建路由的功能
      routes:
        - id: ribbon-customer
          uri: lb://demo-ribbon-customer
          order: 0
          predicates:
            - Path=/gateway_ribbon/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

        - id: feign-customer
          uri: lb://demo-feign-customer
          order: 0
          predicates:
            - Path=/gateway_feign/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            
  sleuth:
    sampler:
      probability: 1  #采样频率
    web:
      enabled: true

#  zipkin:
#    base-url: http://127.0.0.1:9411/
     
  zipkin:
    sender:
      type: rabbit

  rabbitmq:
    host: 192.168.56.26
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: /

logging:
   file: ./logs/server-${spring.application.name}.log
   
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: ALWAYS

info:
  app:
    name: ${spring.application.name}-${server.port}
  company:
    name: example.com
  build:
    group: com.example.springcloud
    artifactId: spring-cloud-gradle-zuul
    version: 0.0.1-SNAPSHOT
