server:
  port: 8094

spring:
  application:
    name: demo-oauth2-client-user

  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8769

  cloud:
    consul: 
      host: 192.168.56.28
      port: 8500
      discovery:
        acl-token: 47eca91b-a5e7-e82d-6424-dba7637e0737
        register: true
        hostname: 192.168.56.1
        serviceName: ${spring.application.name}
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.consul.discovery.hostname}
        healthCheckInterval: 15s

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8093/oauth/authorize
      access-token-uri: http://localhost:8093/oauth/token
      
#    resource:
#      jwt:
#        key-uri: http://localhost:8093/oauth/token_key
#        key-value: dev

    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8093/oauth/check_token
      
logging:
   file: ./logs/server-${spring.application.name}.log
   
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: ALWAYS

info:
  app:
    name: ${spring.application.name}-${server.port}
  company:
    name: example.com
  build:
    group: com.example.springcloud
    artifactId: spring-cloud-gradle-client-user
    version: 0.0.1-SNAPSHOT
