spring:
  datasource:
     url: jdbc:mysql://192.168.56.22:3306/springcloud_task?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      bindings:
        myInput:
          destination: minestream
        myOutput:
          destination: minestream

    task:
      closecontext-enabled: false # 执行完成后，关闭服务
      
    bus:
      enabled: true
      trace: 
        enabled: true

  rabbitmq:
    host: 192.168.56.26
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: /

  sleuth:
    sampler:
      probability: 1  #采样频率
    web:
      enabled: true

#  zipkin:
#    base-url: http://localhost:9411/

  zipkin:
    sender:
      type: rabbit

  #quartz 任务调度框架
  quartz:
    job-store-type: jdbc #数据库方式
    jdbc:
     initialize-schema: never #不初始化表结构
    properties:
     org:
      quartz:
       scheduler:
        instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
        instanceName: clusteredScheduler #quartzScheduler
        jobStore:
         acquireTriggersWithinLock: true #在锁定状态下获取触发器
         class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
         driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
         useProperties: true #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
         tablePrefix: QRTZ_ #数据库表前缀
         misfireThreshold: 6000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
         clusterCheckinInterval: 5000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
         isClustered: false #打开群集功能,集群模式需要在多台服务器上做时间同步或者使用zookeeper去解决
        threadPool: #连接池
         class: org.quartz.simpl.SimpleThreadPool
         threadCount: 10 #最大线程个数
         threadPriority: 5 #线程优先级
         threadsInheritContextClassLoaderOfInitializingThread: true
    startup-delay: 30
    overwrite-existing-jobs: true

